type = "service_account"
project_id = "capstone-project-462912"
private_key_id = "6fb576b433fa5e44233c1b72e6549876656566af"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDSrEbr8Cl/ztJB
/ykVkNOc86ssaxVmXfdzFqbVXZPPFHKZZcV2g66ejigALi5+SALnv/0aXrGxybDf
WasXSRnzGZ6WJoOr6yOF7uptSoTMJT+PL73Iz5g+knLZ7HKlO+9ghGiJzc79/AX5
oJOUREybGqdJx/R0dzGgQeMqmj18EXo8xeaREMTKohDHhnMY25u5od1UqGTV65dc
riLKhE9xDISZR/hwaMN6K4PXzH7hcdHNpGTbSwmPgrlZ1s/snMBNucZzIc2nZmzv
wlWSGmA80oh78H+Ydn7zRgRV0pjaHrnVQ0w494lYVaKGANPTWUPsE25Z/KSBUoJY
e7E/2FWdAgMBAAECggEADv5p5x2RpoyuvuRieoFzPibC1lzMtMYX+B3y7m6ZjXx0
EjeBupyb+fboy+fS2/P+GPEQxNFb2Okfkys2QmhWgMx1p/7CZ6L1mpuqyEUsdxG+
Q0+aNJzpxfz1paLuyenJG1fGekBRQhcEydkZh8zl8t1jw0bdlB3DmhdLtrAsPhR9
9t/7DjjFKptTFCGI/8jyY7yYq9icLZqQPKr8UefWCQ7SXk6755NLcIj5r/vuTBST
mnSsCSDCc9BwuVOK+f9hKj5SaZqx7adN2v/Ts+3JCcFlyads29gIfoa7px2D8VcP
IJJwZI5GLGyM6sSPBRFrIIXtIxwBgcrwjkR31TolAQKBgQDsssSndAMvHZDe/UrC
EcwYVIfWBSNbubjGgsL97hqcNOfpBDUyMod3sU9ieAyf/A+38bcD/LoMr76cDYBk
PF1HetF9mlInIOYNNNuHCMUN10G6c48t4wICqLRA3nYvUc5neTuY69OfKefiBfSw
Nf/nypNhU4O+jFiWZwvE8pLQQQKBgQDj2jZqS+pv7m0R/J7ARJbUrZYxEmGPfhJn
9EA76yG2jVfrc1mscoDhnE6y6XB0nt0KotBapE73ZAaIJyqDwM20odUFSb1KML2d
kX/cEdv9/byXWLgxDlZfNVW6b9nSAQqcZpd7TREtacrapPVpBw0PQlF49oeS0V5E
pL5ruVcuXQKBgQDscvi4PtAfdO2PlH/ltlmnxGmdhqx3qOPIij+34u96M++neqiZ
aJijHOEsgLg76VTacABfX0uL+NP0mBg2CYc1LJ+xVUPUCq1FbBQQpNYUqX/jfiT9
tdQAS/8k/hYZ1yLVguniLVLNoNMfmsuAa7EkH91yUDc/Vnv4YyACsj+vAQKBgDl5
Km6nlYwEVSjLUvPmmTEuVAsuusMqJtRn7OfwSIG2p22xm/X+r/m4prVEYuRXyiPL
q8ihV3XZmjgvwO6Y7Ipao9QApKmZH8smD11gd+BaZ365l0RwfGLpniU333a0YovO
6PjmGKYe4FdEcs66Q5YMwWZEsS/cde3UrF+Z0Z7VAoGAESocRcziSnHOJSLdhmPD
+mccOBEpo94Nk6m9rbVoFyrlO2uOY0Drc+Jfz2nI1zIMDXdWsZoHO1wgTqYH6/Pv
LeT24r3FMfbNbWKwm3ZWiN6oLRK1TLelS+CzV8FIR8zxMj7QPHhANVgqgKaWClR7
CmFFzlqB2+K5TscycfkUO20=
-----END PRIVATE KEY-----
"""
client_email = "feedback-sheet-writer@capstone-project-462912.iam.gserviceaccount.com"
client_id = "115558228394614231627"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/feedback-sheet-writer%40capstone-project-462912.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
